import 'dart:convert';
import 'package:archive/archive.dart';
// ignore: avoid_web_libraries_in_flutter
import 'dart:html' as html;

class ProjectGenerator {
  static const String _defaultSdkVersion = '5.1.0(18)';

  static Future<void> generateAndDownload({
    required String projectName,
    required String bundleId,
    required String description,
    required String primaryColor,
    required String secondaryColor,
    required String tertiaryColor,
    required bool isDarkMode,
    required List<Map<String, dynamic>> selectedWidgets,
    required List<Map<String, dynamic>> selectedManagers,
    required List<Map<String, dynamic>> models,
    String? sdkVersion,
  }) async {
    final archive = Archive();
    final resolvedSdkVersion = (sdkVersion == null || sdkVersion.trim().isEmpty)
        ? _defaultSdkVersion
        : sdkVersion.trim();
    final apiVersion = _extractApiVersion(resolvedSdkVersion);

    _addProjectFiles(
      archive,
      projectName,
      bundleId,
      description,
      resolvedSdkVersion,
      apiVersion,
      primaryColor,
      secondaryColor,
      tertiaryColor,
      isDarkMode,
      selectedWidgets,
      selectedManagers,
      models,
    );

    final zipData = ZipEncoder().encode(archive);
    if (zipData != null) {
      final blob = html.Blob([zipData], 'application/zip');
      final url = html.Url.createObjectUrlFromBlob(blob);
      html.AnchorElement(href: url)
        ..setAttribute('download', '$projectName.zip')
        ..click();
      html.Url.revokeObjectUrl(url);
    }
  }

  static void _addProjectFiles(
    Archive archive,
    String projectName,
    String bundleId,
    String description,
    String sdkVersion,
    int apiVersion,
    String primaryColor,
    String secondaryColor,
    String tertiaryColor,
    bool isDarkMode,
    List<Map<String, dynamic>> selectedWidgets,
    List<Map<String, dynamic>> selectedManagers,
    List<Map<String, dynamic>> models,
  ) {
    final projectPath = projectName;

    _addFile(archive, '$projectPath/README.md', _generateReadme(projectName, description));
    _addFile(archive, '$projectPath/AppScope/app.json5', _generateAppJson(bundleId, projectName, apiVersion));
    _addFile(archive, '$projectPath/build-profile.json5', _generateBuildProfile(sdkVersion));
    _addFile(archive, '$projectPath/oh-package.json5', _generateOhPackage(projectName));
    _addFile(archive, '$projectPath/hvigorfile.ts', _generateHvigorfile());

    // Core module
    _addFile(archive, '$projectPath/core/Index.ets', _generateCoreIndex(selectedManagers));
    _addFile(archive, '$projectPath/core/src/main/module.json5', _generateSharedModuleJson('core'));
    _addFile(
      archive,
      '$projectPath/core/src/main/ets/theme/AppTheme.ets',
      _generateTheme(primaryColor, secondaryColor, tertiaryColor, isDarkMode),
    );
    for (final m in selectedManagers) {
      final className = (m['className'] ?? 'Manager').toString();
      final code = (m['code'] ?? '').toString();
      _addFile(archive, '$projectPath/core/src/main/ets/managers/$className.ets', code);
    }
    for (final model in models) {
      _addFile(
        archive,
        '$projectPath/core/src/main/ets/models/${model['name']}.ets',
        _generateModelCode(model),
      );
    }

    // UIKit module
    _addFile(archive, '$projectPath/uikit/Index.ets', _generateUIKitIndex(selectedWidgets));
    _addFile(archive, '$projectPath/uikit/src/main/module.json5', _generateSharedModuleJson('uikit'));
    for (final widget in selectedWidgets) {
      _addFile(
        archive,
        '$projectPath/uikit/src/main/ets/widgets/${widget['title'].toString().replaceAll(' ', '')}.ets',
        (widget['code'] ?? '// Widget code').toString(),
      );
    }

    // Entry module
    _addFile(
      archive,
      '$projectPath/entry/src/main/module.json5',
      _generateEntryModuleJson(selectedManagers),
    );
    _addFile(
      archive,
      '$projectPath/entry/src/main/ets/pages/Index.ets',
      _generateIndexPage(projectName, selectedWidgets, selectedManagers),
    );
    _addFile(
      archive,
      '$projectPath/entry/src/main/ets/entryability/EntryAbility.ets',
      _generateEntryAbility(),
    );
  }

  static void _addFile(Archive archive, String path, String content) {
    final bytes = utf8.encode(content);
    archive.addFile(ArchiveFile(path, bytes.length, bytes));
  }

  static String _generateReadme(String projectName, String description) {
    return '''# $projectName

$description

## Generated by ArkUI Build

### Project Structure

```
$projectName/
├── entry/   # HAP
├── core/    # shared (theme + managers + models)
├── uikit/   # shared (widgets/components)
├── AppScope/
│   └── app.json5
├── build-profile.json5
├── oh-package.json5
└── README.md
```
''';
  }

  static String _generateAppJson(String bundleId, String appName, int apiVersion) {
    return '''{
  "app": {
    "bundleName": "$bundleId",
    "vendor": "example",
    "versionCode": 1000000,
    "versionName": "1.0.0",
    "icon": "\$media:app_icon",
    "label": "\$string:app_name",
    "description": "$appName - Generated by ArkUI Build",
    "minAPIVersion": $apiVersion,
    "targetAPIVersion": $apiVersion,
    "apiReleaseType": "Release"
  }
}
''';
  }

  static String _generateBuildProfile(String sdkVersion) {
    return '''{
  "app": {
    "compileSdkVersion": "$sdkVersion",
    "compatibleSdkVersion": "$sdkVersion",
    "targetSdkVersion": "$sdkVersion",
    "signingConfigs": [],
    "products": [{
      "name": "default",
      "signingConfig": "default",
      "compileSdkVersion": "$sdkVersion",
      "compatibleSdkVersion": "$sdkVersion",
      "targetSdkVersion": "$sdkVersion"
    }],
    "buildOption": {
      "strictMode": {
        "caseSensitiveCheck": true
      }
    }
  },
  "modules": [{
    "name": "entry",
    "srcPath": "./entry",
    "targets": [{
      "name": "default",
      "applyToProducts": ["default"]
    }]
  },{
    "name": "core",
    "srcPath": "./core",
    "targets": [{
      "name": "default",
      "applyToProducts": ["default"]
    }]
  },{
    "name": "uikit",
    "srcPath": "./uikit",
    "targets": [{
      "name": "default",
      "applyToProducts": ["default"]
    }]
  }]
}
''';
  }

  static String _generateOhPackage(String projectName) {
    return '''{
  "name": "$projectName",
  "version": "1.0.0",
  "description": "Generated by ArkUI Build",
  "main": "",
  "author": "",
  "license": "ISC",
  "dependencies": {}
}
''';
  }

  static int _extractApiVersion(String sdkVersion) {
    final match = RegExp(r'\((\d+)\)').firstMatch(sdkVersion);
    if (match != null) {
      return int.tryParse(match.group(1) ?? '') ?? 18;
    }
    return 18;
  }

  static String _generateHvigorfile() {
    return "export { appTasks } from '@ohos/hvigor-ohos-plugin';\n";
  }

  static String _generateTheme(String primary, String secondary, String tertiary, bool isDark) {
    return '''export class AppTheme {
  static readonly PRIMARY = '$primary';
  static readonly SECONDARY = '$secondary';
  static readonly TERTIARY = '$tertiary';

  static readonly BACKGROUND = '${isDark ? '#121212' : '#FAFAFA'}';
  static readonly TEXT_PRIMARY = '${isDark ? '#FFFFFF' : '#212121'}';
  static readonly TEXT_SECONDARY = '${isDark ? '#B3B3B3' : '#757575'}';
}
''';
  }

  static String _generateModelCode(Map<String, dynamic> model) {
    return '''export class ${model['name']} {
  constructor() {}
}
''';
  }

  static String _generateIndexPage(
    String projectName,
    List<Map<String, dynamic>> widgets,
    List<Map<String, dynamic>> managers,
  ) {
    final widgetSections = widgets.map((widget) {
      final title = (widget['title'] ?? 'Widget').toString();
      final fileName = title.replaceAll(' ', '');
      return '''
      // Section: $title (see uikit/$fileName.ets)
      Text('$title')
        .fontSize(16)
        .fontWeight(FontWeight.Medium)
        .fontColor(AppTheme.TEXT_PRIMARY)
        .margin({ top: 12, bottom: 8 })''';
    }).join('\n');

    return '''import { AppTheme } from '@$projectName/core';

@Entry
@Component
struct Index {
  @State message: string = 'Welcome to $projectName';

  build() {
    Scroll() {
      Column() {
        Text(this.message)
          .fontSize(24)
          .fontWeight(FontWeight.Bold)
          .fontColor(AppTheme.TEXT_PRIMARY)
          .margin({ top: 20, bottom: 12 })

        Text('${widgets.length} widgets, ${managers.length} managers selected from catalog')
          .fontSize(14)
          .fontColor(AppTheme.TEXT_SECONDARY)
          .margin({ bottom: 16 })
$widgetSections
      }
      .width('100%')
      .padding(20)
    }
    .width('100%')
    .height('100%')
    .backgroundColor(AppTheme.BACKGROUND)
  }
}
''';
  }

  static String _generateEntryAbility() {
    return '''import UIAbility from '@ohos.app.ability.UIAbility';
import window from '@ohos.window';

export default class EntryAbility extends UIAbility {
  onWindowStageCreate(windowStage: window.WindowStage) {
    windowStage.loadContent('pages/Index', (err) => {
      if (err.code) {
        console.error('Failed to load the content. Cause: ' + JSON.stringify(err));
      }
    });
  }
}
''';
  }

  static String _generateEntryModuleJson(List<Map<String, dynamic>> managers) {
    final permissionMap = <String, String>{};
    for (final m in managers) {
      final raw = m['permissions'];
      if (raw is List) {
        for (final p in raw) {
          final value = p.toString().trim();
          if (value.isNotEmpty) {
            final key = value.toUpperCase();
            permissionMap.putIfAbsent(key, () => value);
          }
        }
      }
    }
    final permissions = permissionMap.values.toSet();
    final permissionLines = permissions.map((p) => '      "$p"').join(',\n');
    final requestPermissionsBlock = permissions.isEmpty
        ? ''
        : ',\n    "requestPermissions": [\n$permissionLines\n    ]';

    return '''{
  "module": {
    "name": "entry",
    "type": "entry",
    "description": "Entry module",
    "mainElement": "EntryAbility",
    "deviceTypes": ["phone", "tablet", "2in1"],
    "deliveryWithInstall": true,
    "installationFree": false,
    "pages": "src/main/ets/pages"$requestPermissionsBlock
  }
}
''';
  }

  static String _generateSharedModuleJson(String name) {
    return '''{
  "module": {
    "name": "$name",
    "type": "shared",
    "description": "$name shared module",
    "deviceTypes": ["phone", "tablet", "2in1"],
    "deliveryWithInstall": true,
    "installationFree": false
  }
}
''';
  }

  static String _generateCoreIndex(List<Map<String, dynamic>> managers) {
    final exports = <String>[
      "export { AppTheme } from './src/main/ets/theme/AppTheme';",
    ];
    for (final m in managers) {
      final exportCode = (m['exportCode'] ?? '').toString().trim();
      if (exportCode.isNotEmpty) {
        exports.add(exportCode);
        continue;
      }

      final className = (m['className'] ?? '').toString().trim();
      if (className.isNotEmpty) {
        exports.add("export { $className } from './src/main/ets/managers/$className';");
      }
    }
    return '${exports.join('\n')}\n';
  }

  static String _generateUIKitIndex(List<Map<String, dynamic>> widgets) {
    final exports = <String>[];
    for (final w in widgets) {
      final name = w['title'].toString().replaceAll(' ', '');
      exports.add("export * from './src/main/ets/widgets/$name';");
    }
    return '${exports.join('\n')}\n';
  }
}

