steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --tag
      - ${_IMAGE}
      - .
    timeout: 3600s

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_IMAGE}

images:
  - ${_IMAGE}

options:
  machineType: E2_HIGHCPU_32
  diskSizeGb: 200
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _IMAGE: europe-west1-docker.pkg.dev/arkuibuilder/arkuibuild/playground:latest

timeout: 4200s
