import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:google_fonts/google_fonts.dart';
import '../theme/app_chrome.dart';
import '../widgets/code_viewer.dart';

class ThemeBuilderScreen extends StatefulWidget {
  const ThemeBuilderScreen({super.key});

  @override
  State<ThemeBuilderScreen> createState() => _ThemeBuilderScreenState();
}

class _ThemeBuilderScreenState extends State<ThemeBuilderScreen> {
  // Default colors
  Color primaryColor = AppChrome.ink;
  Color secondaryColor = const Color(0xFF03DAC6);
  Color tertiaryColor = const Color(0xFFFF6B6B);
  
  // Theme mode selector
  bool _isDarkMode = false;

  String get generatedThemeCode {
    return _isDarkMode 
        ? _generateArkTSTheme(primaryColor, secondaryColor, tertiaryColor, isDark: true)
        : _generateArkTSTheme(primaryColor, secondaryColor, tertiaryColor, isDark: false);
  }

  String _generateArkTSTheme(Color primary, Color secondary, Color tertiary, {required bool isDark}) {
    // Helper function to convert Color to hex
    String colorToHex(Color color) {
      return '#${color.value.toRadixString(16).substring(2).toUpperCase()}';
    }

    // Helper function to lighten a color
    Color lighten(Color color, [double amount = 0.1]) {
      final hsl = HSLColor.fromColor(color);
      final lightness = (hsl.lightness + amount).clamp(0.0, 1.0);
      return hsl.withLightness(lightness).toColor();
    }

    // Helper function to darken a color
    Color darken(Color color, [double amount = 0.1]) {
      final hsl = HSLColor.fromColor(color);
      final lightness = (hsl.lightness - amount).clamp(0.0, 1.0);
      return hsl.withLightness(lightness).toColor();
    }

    // Helper function to get contrasting color (white or black)
    String getContrastColor(Color color) {
      final luminance = color.computeLuminance();
      return luminance > 0.5 ? '#000000' : '#FFFFFF';
    }

    // Helper function to desaturate color for dark mode
    Color desaturate(Color color, [double amount = 0.2]) {
      final hsl = HSLColor.fromColor(color);
      final saturation = (hsl.saturation - amount).clamp(0.0, 1.0);
      return hsl.withSaturation(saturation).toColor();
    }

    // Adjust colors for dark mode (slightly desaturated and lighter)
    Color adjustForDarkMode(Color color) {
      if (!isDark) return color;
      
      final hsl = HSLColor.fromColor(color);
      // Reduce saturation and increase lightness for dark mode
      final newSaturation = (hsl.saturation * 0.85).clamp(0.0, 1.0);
      final newLightness = (hsl.lightness * 1.15).clamp(0.0, 0.75); // Max 0.75 to keep it visible
      
      return hsl
          .withSaturation(newSaturation)
          .withLightness(newLightness)
          .toColor();
    }

    // Adjusted colors for dark mode
    final adjustedPrimary = adjustForDarkMode(primary);
    final adjustedSecondary = adjustForDarkMode(secondary);
    final adjustedTertiary = adjustForDarkMode(tertiary);

    return '''
// ArkUI Theme Configuration - ${isDark ? 'DARK MODE' : 'LIGHT MODE'}
// Generated by ArkUI Build Theme Designer
// Date: ${DateTime.now().toString().split('.')[0]}

export class AppTheme${isDark ? 'Dark' : 'Light'} {
  // Primary Colors
  static readonly PRIMARY = '${colorToHex(adjustedPrimary)}';
  static readonly PRIMARY_LIGHT = '${colorToHex(lighten(adjustedPrimary, 0.15))}';
  static readonly PRIMARY_DARK = '${colorToHex(darken(adjustedPrimary, 0.15))}';
  static readonly ON_PRIMARY = '${getContrastColor(adjustedPrimary)}';
  
  // Secondary Colors
  static readonly SECONDARY = '${colorToHex(adjustedSecondary)}';
  static readonly SECONDARY_LIGHT = '${colorToHex(lighten(adjustedSecondary, 0.15))}';
  static readonly SECONDARY_DARK = '${colorToHex(darken(adjustedSecondary, 0.15))}';
  static readonly ON_SECONDARY = '${getContrastColor(adjustedSecondary)}';
  
  // Tertiary/Accent Colors
  static readonly TERTIARY = '${colorToHex(adjustedTertiary)}';
  static readonly TERTIARY_LIGHT = '${colorToHex(lighten(adjustedTertiary, 0.15))}';
  static readonly TERTIARY_DARK = '${colorToHex(darken(adjustedTertiary, 0.15))}';
  static readonly ON_TERTIARY = '${getContrastColor(adjustedTertiary)}';
  
  // Background Colors
  static readonly BACKGROUND = '${isDark ? '#121212' : '#FAFAFA'}';
  static readonly SURFACE = '${isDark ? '#1E1E1E' : '#FFFFFF'}';
  static readonly ON_BACKGROUND = '${isDark ? '#FFFFFF' : '#000000'}';
  static readonly ON_SURFACE = '${isDark ? '#FFFFFF' : '#000000'}';
  
  // Error Colors
  static readonly ERROR = '${isDark ? '#CF6679' : '#B00020'}';
  static readonly ON_ERROR = '#FFFFFF';
  
  // Text Colors
  static readonly TEXT_PRIMARY = '${isDark ? '#FFFFFF' : '#212121'}';
  static readonly TEXT_SECONDARY = '${isDark ? '#B3B3B3' : '#757575'}';
  static readonly TEXT_DISABLED = '${isDark ? '#666666' : '#BDBDBD'}';
  
  // Border & Divider
  static readonly BORDER = '${isDark ? '#333333' : '#E0E0E0'}';
  static readonly DIVIDER = '${isDark ? '#2A2A2A' : '#EEEEEE'}';
  
  // Shadow
  static readonly SHADOW = '${isDark ? 'rgba(0, 0, 0, 0.5)' : 'rgba(0, 0, 0, 0.15)'}';
  
  // Card & Container
  static readonly CARD_BACKGROUND = '${isDark ? '#252525' : '#FFFFFF'}';
  static readonly CONTAINER_BACKGROUND = '${isDark ? '#1A1A1A' : '#F5F5F5'}';
}

// Usage Example:
@Component
struct ThemedButton {
  build() {
    Button('Click Me')
      .backgroundColor(AppTheme${isDark ? 'Dark' : 'Light'}.PRIMARY)
      .fontColor(AppTheme${isDark ? 'Dark' : 'Light'}.ON_PRIMARY)
      .borderRadius(8)
      .padding({ left: 24, right: 24, top: 12, bottom: 12 })
  }
}

@Component
struct ThemedCard {
  build() {
    Column() {
      Text('Card Title')
        .fontSize(18)
        .fontWeight(FontWeight.Bold)
        .fontColor(AppTheme${isDark ? 'Dark' : 'Light'}.TEXT_PRIMARY)
      
      Text('Card description goes here')
        .fontSize(14)
        .fontColor(AppTheme${isDark ? 'Dark' : 'Light'}.TEXT_SECONDARY)
        .margin({ top: 8 })
    }
    .padding(16)
    .backgroundColor(AppTheme${isDark ? 'Dark' : 'Light'}.CARD_BACKGROUND)
    .borderRadius(12)
    .shadow({
      radius: 8,
      color: AppTheme${isDark ? 'Dark' : 'Light'}.SHADOW,
      offsetX: 0,
      offsetY: 2
    })
  }
}
''';
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: AppChrome.canvas,
      appBar: AppChrome.appBar(
        context: context,
        title: 'Theme Builder',
        icon: Icons.palette_rounded,
      ),
      body: LayoutBuilder(
        builder: (context, constraints) {
          final isMobile = constraints.maxWidth < 768;
          
          if (isMobile) {
            return _buildMobileLayout();
          } else {
            return _buildDesktopLayout();
          }
        },
      ),
    );
  }

  Widget _buildMobileLayout() {
    return SingleChildScrollView(
      padding: const EdgeInsets.all(16),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: [
          _buildColorPickers(),
          const SizedBox(height: 24),
          _buildPreview(),
          const SizedBox(height: 24),
          _buildCodeSection(),
        ],
      ),
    );
  }

  Widget _buildDesktopLayout() {
    return Row(
      children: [
        // Left side - Color pickers and preview
        Container(
          width: 400,
          decoration: BoxDecoration(
            color: Colors.white,
            boxShadow: [
              BoxShadow(
                color: Colors.black.withOpacity(0.05),
                blurRadius: 10,
                offset: const Offset(2, 0),
              ),
            ],
          ),
          child: SingleChildScrollView(
            padding: const EdgeInsets.all(24),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.stretch,
              children: [
                _buildColorPickers(),
                const SizedBox(height: 24),
                _buildPreview(),
              ],
            ),
          ),
        ),
        // Right side - Code output
        Expanded(
          child: _buildCodeSection(),
        ),
      ],
    );
  }

  Widget _buildColorPickers() {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Row(
          mainAxisAlignment: MainAxisAlignment.spaceBetween,
          children: [
            Expanded(
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(
                    'Choose Your Colors',
                    style: AppChrome.body(
                      fontSize: 20,
                      fontWeight: FontWeight.bold,
                      color: AppChrome.ink,
                    ),
                  ),
                  const SizedBox(height: 4),
                  Text(
                    'Select 3 main colors to generate your theme',
                    style: AppChrome.body(
                      fontSize: 14,
                      color: AppChrome.muted,
                    ),
                  ),
                ],
              ),
            ),
          ],
        ),
        const SizedBox(height: 16),
        
        // Theme Mode Toggle
        Container(
          padding: const EdgeInsets.all(4),
          decoration: BoxDecoration(
            color: const Color(0xFFF3F4F6),
            borderRadius: BorderRadius.circular(12),
          ),
          child: Row(
            children: [
              Expanded(
                child: InkWell(
                  onTap: () {
                    setState(() => _isDarkMode = false);
                  },
                  borderRadius: BorderRadius.circular(10),
                  child: Container(
                    padding: const EdgeInsets.symmetric(vertical: 12),
                    decoration: BoxDecoration(
                      color: !_isDarkMode ? Colors.white : Colors.transparent,
                      borderRadius: BorderRadius.circular(10),
                      boxShadow: !_isDarkMode
                          ? [
                              BoxShadow(
                                color: Colors.black.withOpacity(0.1),
                                blurRadius: 8,
                                offset: const Offset(0, 2),
                              ),
                            ]
                          : null,
                    ),
                    child: Row(
                      mainAxisAlignment: MainAxisAlignment.center,
                      children: [
                        Icon(
                          Icons.light_mode,
                          size: 18,
                          color: !_isDarkMode
                              ? AppChrome.ink
                              : const Color(0xFF94A3B8),
                        ),
                        const SizedBox(width: 8),
                        Text(
                          'Light Mode',
                          style: AppChrome.body(
                            fontSize: 14,
                            fontWeight: !_isDarkMode ? FontWeight.w600 : FontWeight.normal,
                            color: !_isDarkMode
                                ? AppChrome.ink
                                : const Color(0xFF94A3B8),
                          ),
                        ),
                      ],
                    ),
                  ),
                ),
              ),
              Expanded(
                child: InkWell(
                  onTap: () {
                    setState(() => _isDarkMode = true);
                  },
                  borderRadius: BorderRadius.circular(10),
                  child: Container(
                    padding: const EdgeInsets.symmetric(vertical: 12),
                    decoration: BoxDecoration(
                      color: _isDarkMode ? Colors.white : Colors.transparent,
                      borderRadius: BorderRadius.circular(10),
                      boxShadow: _isDarkMode
                          ? [
                              BoxShadow(
                                color: Colors.black.withOpacity(0.1),
                                blurRadius: 8,
                                offset: const Offset(0, 2),
                              ),
                            ]
                          : null,
                    ),
                    child: Row(
                      mainAxisAlignment: MainAxisAlignment.center,
                      children: [
                        Icon(
                          Icons.dark_mode,
                          size: 18,
                          color: _isDarkMode
                              ? AppChrome.ink
                              : const Color(0xFF94A3B8),
                        ),
                        const SizedBox(width: 8),
                        Text(
                          'Dark Mode',
                          style: AppChrome.body(
                            fontSize: 14,
                            fontWeight: _isDarkMode ? FontWeight.w600 : FontWeight.normal,
                            color: _isDarkMode
                                ? AppChrome.ink
                                : const Color(0xFF94A3B8),
                          ),
                        ),
                      ],
                    ),
                  ),
                ),
              ),
            ],
          ),
        ),
        
        const SizedBox(height: 24),
        _buildColorPicker(
          label: 'Primary Color',
          description: 'Main brand color for buttons and key elements',
          color: primaryColor,
          onColorChanged: (color) {
            setState(() => primaryColor = color);
          },
        ),
        const SizedBox(height: 20),
        _buildColorPicker(
          label: 'Secondary Color',
          description: 'Accent color for highlights and secondary actions',
          color: secondaryColor,
          onColorChanged: (color) {
            setState(() => secondaryColor = color);
          },
        ),
        const SizedBox(height: 20),
        _buildColorPicker(
          label: 'Tertiary Color',
          description: 'Additional accent for diversity and emphasis',
          color: tertiaryColor,
          onColorChanged: (color) {
            setState(() => tertiaryColor = color);
          },
        ),
      ],
    );
  }

  Widget _buildColorPicker({
    required String label,
    required String description,
    required Color color,
    required ValueChanged<Color> onColorChanged,
  }) {
    // Get adjusted color for dark mode
    Color getAdjustedColor() {
      if (!_isDarkMode) return color;
      
      final hsl = HSLColor.fromColor(color);
      final newSaturation = (hsl.saturation * 0.85).clamp(0.0, 1.0);
      final newLightness = (hsl.lightness * 1.15).clamp(0.0, 0.75);
      
      final adjusted = hsl
          .withSaturation(newSaturation)
          .withLightness(newLightness)
          .toColor();
      
      // Debug
      print('$label: isDark=$_isDarkMode, original=#${color.value.toRadixString(16).substring(2).toUpperCase()}, adjusted=#${adjusted.value.toRadixString(16).substring(2).toUpperCase()}');
      
      return adjusted;
    }
    
    final displayColor = getAdjustedColor();
    
    return Container(
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: AppChrome.canvas,
        borderRadius: BorderRadius.circular(12),
        border: Border.all(color: const Color(0xFFE5E7EB)),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            children: [
              Container(
                width: 40,
                height: 40,
                decoration: BoxDecoration(
                  color: displayColor,
                  borderRadius: BorderRadius.circular(8),
                  border: Border.all(color: Colors.black12, width: 2),
                  boxShadow: [
                    BoxShadow(
                      color: Colors.black.withOpacity(0.1),
                      blurRadius: 4,
                      offset: const Offset(0, 2),
                    ),
                  ],
                ),
              ),
              const SizedBox(width: 12),
              Expanded(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text(
                      label,
                      style: AppChrome.body(
                        fontSize: 16,
                        fontWeight: FontWeight.w600,
                        color: AppChrome.ink,
                      ),
                    ),
                    const SizedBox(height: 2),
                    Text(
                      '#${displayColor.value.toRadixString(16).substring(2).toUpperCase()}',
                      style: GoogleFonts.jetBrainsMono(
                        fontSize: 12,
                        color: AppChrome.muted,
                      ),
                    ),
                    if (_isDarkMode)
                      Text(
                        'Adjusted for dark mode',
                        style: AppChrome.body(
                          fontSize: 10,
                          color: const Color(0xFF94A3B8),
                          fontStyle: FontStyle.italic,
                        ),
                      ),
                  ],
                ),
              ),
            ],
          ),
          const SizedBox(height: 8),
          Text(
            description,
            style: AppChrome.body(
              fontSize: 12,
              color: const Color(0xFF94A3B8),
            ),
          ),
          const SizedBox(height: 12),
          ElevatedButton.icon(
            onPressed: () => _showColorPickerDialog(color, onColorChanged),
            icon: const Icon(Icons.colorize, size: 18),
            label: const Text('Pick Color'),
            style: ElevatedButton.styleFrom(
              backgroundColor: AppChrome.ink,
              foregroundColor: Colors.white,
              padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 10),
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.circular(8),
              ),
            ),
          ),
        ],
      ),
    );
  }

  void _showColorPickerDialog(Color currentColor, ValueChanged<Color> onColorChanged) {
    showDialog(
      context: context,
      builder: (dialogContext) => Dialog(
        child: Container(
          width: 400,
          padding: const EdgeInsets.all(20),
          child: Column(
            mainAxisSize: MainAxisSize.min,
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Text(
                'Pick a Color',
                style: AppChrome.body(
                  fontWeight: FontWeight.bold,
                  fontSize: 18,
                ),
              ),
              const SizedBox(height: 16),
              SizedBox(
                height: 400,
                child: GridView.builder(
                  gridDelegate: const SliverGridDelegateWithFixedCrossAxisCount(
                    crossAxisCount: 5,
                    crossAxisSpacing: 12,
                    mainAxisSpacing: 12,
                    childAspectRatio: 0.85,
                  ),
                  itemCount: _predefinedColors.length,
                  itemBuilder: (context, index) {
                    final color = _predefinedColors[index];
                    final isSelected = currentColor.value == color.value;
                    final hexCode = '#${color.value.toRadixString(16).substring(2).toUpperCase()}';
                    
                    return Column(
                      mainAxisSize: MainAxisSize.min,
                      children: [
                        Expanded(
                          child: InkWell(
                            onTap: () {
                              onColorChanged(color);
                              Navigator.pop(dialogContext);
                            },
                            borderRadius: BorderRadius.circular(8),
                            child: Container(
                              decoration: BoxDecoration(
                                color: color,
                                borderRadius: BorderRadius.circular(8),
                                border: Border.all(
                                  color: isSelected ? Colors.black : Colors.black12,
                                  width: isSelected ? 3 : 1,
                                ),
                              ),
                              child: isSelected
                                  ? const Center(
                                      child: Icon(
                                        Icons.check_circle,
                                        color: Colors.white,
                                        size: 20,
                                      ),
                                    )
                                  : null,
                            ),
                          ),
                        ),
                        const SizedBox(height: 4),
                        InkWell(
                          onTap: () {
                            Clipboard.setData(ClipboardData(text: hexCode));
                            ScaffoldMessenger.of(context).showSnackBar(
                              SnackBar(
                                content: Text(
                                  '$hexCode copied!',
                                  style: AppChrome.body(fontSize: 12),
                                ),
                                backgroundColor: Colors.green,
                                duration: const Duration(seconds: 1),
                                behavior: SnackBarBehavior.floating,
                                margin: const EdgeInsets.all(8),
                                shape: RoundedRectangleBorder(
                                  borderRadius: BorderRadius.circular(8),
                                ),
                              ),
                            );
                          },
                          child: Container(
                            padding: const EdgeInsets.symmetric(horizontal: 4, vertical: 2),
                            child: Text(
                              hexCode,
                              style: GoogleFonts.jetBrainsMono(
                                fontSize: 9,
                                color: AppChrome.muted,
                              ),
                              textAlign: TextAlign.center,
                              maxLines: 1,
                              overflow: TextOverflow.ellipsis,
                            ),
                          ),
                        ),
                      ],
                    );
                  },
                ),
              ),
              const SizedBox(height: 16),
              Row(
                mainAxisAlignment: MainAxisAlignment.end,
                children: [
                  TextButton(
                    onPressed: () => Navigator.pop(dialogContext),
                    child: const Text('Cancel'),
                  ),
                ],
              ),
            ],
          ),
        ),
      ),
    );
  }

  Widget _buildPreview() {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(
          'Theme Preview',
          style: AppChrome.body(
            fontSize: 18,
            fontWeight: FontWeight.bold,
            color: AppChrome.ink,
          ),
        ),
        const SizedBox(height: 16),
        
        // Color palette
        Container(
          padding: const EdgeInsets.all(16),
          decoration: BoxDecoration(
            color: Colors.white,
            borderRadius: BorderRadius.circular(12),
            border: Border.all(color: const Color(0xFFE5E7EB)),
          ),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Text(
                'Color Palette',
                style: AppChrome.body(
                  fontSize: 14,
                  fontWeight: FontWeight.w600,
                  color: AppChrome.muted,
                ),
              ),
              const SizedBox(height: 12),
              _buildColorSwatch('Primary', primaryColor),
              const SizedBox(height: 8),
              _buildColorSwatch('Secondary', secondaryColor),
              const SizedBox(height: 8),
              _buildColorSwatch('Tertiary', tertiaryColor),
            ],
          ),
        ),
        
        const SizedBox(height: 16),
        
        // Component preview
        Container(
          padding: const EdgeInsets.all(16),
          decoration: BoxDecoration(
            color: Colors.white,
            borderRadius: BorderRadius.circular(12),
            border: Border.all(color: const Color(0xFFE5E7EB)),
          ),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Text(
                'Component Examples',
                style: AppChrome.body(
                  fontSize: 14,
                  fontWeight: FontWeight.w600,
                  color: AppChrome.muted,
                ),
              ),
              const SizedBox(height: 12),
              
              // Buttons
              Wrap(
                spacing: 8,
                runSpacing: 8,
                children: [
                  ElevatedButton(
                    onPressed: () {},
                    style: ElevatedButton.styleFrom(
                      backgroundColor: primaryColor,
                      foregroundColor: _getContrastingColor(primaryColor),
                    ),
                    child: const Text('Primary'),
                  ),
                  ElevatedButton(
                    onPressed: () {},
                    style: ElevatedButton.styleFrom(
                      backgroundColor: secondaryColor,
                      foregroundColor: _getContrastingColor(secondaryColor),
                    ),
                    child: const Text('Secondary'),
                  ),
                  ElevatedButton(
                    onPressed: () {},
                    style: ElevatedButton.styleFrom(
                      backgroundColor: tertiaryColor,
                      foregroundColor: _getContrastingColor(tertiaryColor),
                    ),
                    child: const Text('Tertiary'),
                  ),
                ],
              ),
            ],
          ),
        ),
      ],
    );
  }

  Widget _buildColorSwatch(String label, Color color) {
    final light = _lightenColor(color, 0.15);
    final dark = _darkenColor(color, 0.15);
    
    return Row(
      children: [
        Expanded(
          child: Text(
            label,
            style: AppChrome.body(
              fontSize: 12,
              fontWeight: FontWeight.w500,
            ),
          ),
        ),
        _buildColorBox(dark, 'Dark'),
        const SizedBox(width: 4),
        _buildColorBox(color, 'Base'),
        const SizedBox(width: 4),
        _buildColorBox(light, 'Light'),
      ],
    );
  }

  Widget _buildColorBox(Color color, String label) {
    return Column(
      children: [
        Container(
          width: 40,
          height: 40,
          decoration: BoxDecoration(
            color: color,
            borderRadius: BorderRadius.circular(6),
            border: Border.all(color: Colors.black12),
          ),
        ),
        const SizedBox(height: 4),
        Text(
          label,
          style: AppChrome.body(
            fontSize: 9,
            color: const Color(0xFF94A3B8),
          ),
        ),
      ],
    );
  }

  Widget _buildCodeSection() {
    return Container(
      color: AppChrome.canvas,
      padding: const EdgeInsets.all(24),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: [
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Row(
                    children: [
                      Text(
                        'Generated Theme Code',
                        style: AppChrome.body(
                          fontSize: 20,
                          fontWeight: FontWeight.bold,
                          color: AppChrome.ink,
                        ),
                      ),
                      const SizedBox(width: 12),
                      Container(
                        padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 4),
                        decoration: BoxDecoration(
                          color: _isDarkMode 
                              ? AppChrome.ink
                              : const Color(0xFFEEF2FF),
                          borderRadius: BorderRadius.circular(6),
                        ),
                        child: Row(
                          mainAxisSize: MainAxisSize.min,
                          children: [
                            Icon(
                              _isDarkMode ? Icons.dark_mode : Icons.light_mode,
                              size: 14,
                              color: _isDarkMode 
                                  ? Colors.white
                                  : AppChrome.ink,
                            ),
                            const SizedBox(width: 4),
                            Text(
                              _isDarkMode ? 'Dark' : 'Light',
                              style: AppChrome.body(
                                fontSize: 12,
                                fontWeight: FontWeight.w600,
                                color: _isDarkMode 
                                    ? Colors.white
                                    : AppChrome.ink,
                              ),
                            ),
                          ],
                        ),
                      ),
                    ],
                  ),
                  const SizedBox(height: 4),
                  Text(
                    'Copy and paste into your ArkTS project',
                    style: AppChrome.body(
                      fontSize: 14,
                      color: AppChrome.muted,
                    ),
                  ),
                ],
              ),
              ElevatedButton.icon(
                onPressed: () {
                  Clipboard.setData(ClipboardData(text: generatedThemeCode));
                  ScaffoldMessenger.of(context).showSnackBar(
                    SnackBar(
                      content: Row(
                        children: [
                          const Icon(Icons.check_circle, color: Colors.white),
                          const SizedBox(width: 12),
                          Text(
                            'Theme code copied to clipboard!',
                            style: AppChrome.body(),
                          ),
                        ],
                      ),
                      backgroundColor: Colors.green,
                      behavior: SnackBarBehavior.floating,
                      shape: RoundedRectangleBorder(
                        borderRadius: BorderRadius.circular(8),
                      ),
                    ),
                  );
                },
                icon: const Icon(Icons.copy, size: 18),
                label: const Text('Copy Code'),
                style: ElevatedButton.styleFrom(
                  backgroundColor: AppChrome.ink,
                  foregroundColor: Colors.white,
                  padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 16),
                  shape: RoundedRectangleBorder(
                    borderRadius: BorderRadius.circular(8),
                  ),
                ),
              ),
            ],
          ),
          const SizedBox(height: 16),
          Expanded(
            child: CodeViewer(
              code: generatedThemeCode,
              title: 'AppTheme',
            ),
          ),
        ],
      ),
    );
  }

  Color _lightenColor(Color color, double amount) {
    final hsl = HSLColor.fromColor(color);
    final lightness = (hsl.lightness + amount).clamp(0.0, 1.0);
    return hsl.withLightness(lightness).toColor();
  }

  Color _darkenColor(Color color, double amount) {
    final hsl = HSLColor.fromColor(color);
    final lightness = (hsl.lightness - amount).clamp(0.0, 1.0);
    return hsl.withLightness(lightness).toColor();
  }

  Color _getContrastingColor(Color color) {
    final luminance = color.computeLuminance();
    return luminance > 0.5 ? Colors.black : Colors.white;
  }

  // Predefined color palette
  static final List<Color> _predefinedColors = [
    // Reds
    const Color(0xFFFF6B6B),
    const Color(0xFFEE5A6F),
    const Color(0xFFC44569),
    // Oranges
    const Color(0xFFFF9F43),
    const Color(0xFFFC5C65),
    const Color(0xFFFD7272),
    // Yellows
    const Color(0xFFFECA57),
    const Color(0xFFFFD93D),
    const Color(0xFFF8B500),
    // Greens
    const Color(0xFF6BCF7F),
    const Color(0xFF26DE81),
    const Color(0xFF20BF6B),
    // Blues
    const Color(0xFF45AAF2),
    const Color(0xFF4B7BEC),
    const Color(0xFF3867D6),
    // Purples
    AppChrome.ink,
    const Color(0xFF5F27CD),
    const Color(0xFFA55EEA),
    // Pinks
    const Color(0xFFFC427B),
    const Color(0xFFF78FB3),
    const Color(0xFFD980FA),
    // Teals
    const Color(0xFF00D2D3),
    const Color(0xFF1DD1A1),
    const Color(0xFF10AC84),
    // Grays
    const Color(0xFF778CA3),
    const Color(0xFF4B6584),
    const Color(0xFF2C3E50),
    // Others
    const Color(0xFF00B894),
    const Color(0xFF00CEC9),
    const Color(0xFF0984E3),
  ];
}
